POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "rob",
  "password": "12345"
}

###
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZGFhNGRhMS1kNDBlLTRiOTktYmRmYS0yOTFiY2I0MzM5MzgiLCJyb2xlIjoxLCJpYXQiOjE2NjAwNzY3MzYsImV4cCI6MTY2MDY4MTUzNn0.ujHWvAiBKazq9CgzA6qerlLQYozvxKAZknWquCXJues